"""
Report model for storing fetched content
"""
from sqlalchemy import Column, String, Text, DateTime, ForeignKey, Integer, Index
from sqlalchemy.dialects.postgresql import UUID, JSONB, ARRAY
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
import uuid

from .base import Base


class Report(Base):
    """Main content storage for fetched reports"""
    __tablename__ = 'reports'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id = Column(UUID(as_uuid=True), ForeignKey('tenants.id', ondelete='CASCADE'), nullable=False, index=True)

    # Deduplication key (auto-generated by database trigger)
    dedupe_key = Column(String(64), nullable=False, index=True)

    # Report metadata
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True)
    source = Column(String(500))  # e.g., "RSS", "TikTok (@username)"
    provider = Column(String(50), nullable=False, index=True)  # RSS, TikTok, Instagram

    # Content
    brands = Column(ARRAY(Text), default=list)
    title = Column(Text, nullable=False)
    link = Column(Text, nullable=False)
    summary = Column(Text)
    full_text = Column(Text)

    # Analysis results
    sentiment = Column(String(50), index=True)  # positive, neutral, negative, mixed
    topic = Column(String(100))  # product, influencer, lifestyle, trend, corporate
    est_reach = Column(Integer, default=0)

    # Additional metadata
    raw_data = Column(JSONB, default=dict)

    # Processing status
    processing_status = Column(String(50), default='pending', index=True)
    error_message = Column(Text)

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    tenant = relationship("Tenant", back_populates="reports")

    # Composite indexes for common query patterns
    __table_args__ = (
        Index('idx_reports_tenant_status_timestamp', 'tenant_id', 'processing_status', 'timestamp'),
        Index('idx_reports_tenant_provider_timestamp', 'tenant_id', 'provider', 'timestamp'),
        Index('idx_reports_tenant_dedupe', 'tenant_id', 'dedupe_key', unique=True),
    )

    def __repr__(self):
        return f"<Report(id='{self.id}', title='{self.title[:50]}...', provider='{self.provider}')>"

    def to_dict(self):
        """Convert report to dictionary"""
        return {
            'id': str(self.id),
            'tenant_id': str(self.tenant_id),
            'timestamp': self.timestamp.isoformat() if self.timestamp else None,
            'source': self.source,
            'provider': self.provider,
            'brands': self.brands or [],
            'title': self.title,
            'link': self.link,
            'summary': self.summary,
            'full_text': self.full_text,
            'sentiment': self.sentiment,
            'topic': self.topic,
            'est_reach': self.est_reach,
            'raw_data': self.raw_data,
            'processing_status': self.processing_status,
            'error_message': self.error_message,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
        }
