import apiClient from './client';
import type { Brand, PaginatedResponse } from '../types';
import type { Feed } from './feeds';

export const brandsApi = {
  // Get all brands
  getBrands: async (skip: number = 0, limit: number = 1000): Promise<Brand[]> => {
    const response = await apiClient.get<Brand[]>(
      `/api/v1/brands/?skip=${skip}&limit=${limit}`
    );
    return response.data;
  },

  // Get single brand by ID
  getBrand: async (id: string): Promise<Brand> => {
    const response = await apiClient.get<Brand>(`/api/v1/brands/${id}`);
    return response.data;
  },

  // Create new brand
  createBrand: async (data: any): Promise<Brand> => {
    const response = await apiClient.post<Brand>(`/api/v1/brands/`, data);
    return response.data;
  },

  // Update brand
  updateBrand: async (id: string, data: any): Promise<Brand> => {
    const response = await apiClient.put<Brand>(`/api/v1/brands/${id}`, data);
    return response.data;
  },

  // Delete brand
  deleteBrand: async (id: string): Promise<void> => {
    await apiClient.delete(`/api/v1/brands/${id}`);
  },

  // Get brand by name
  getBrandByName: async (brandName: string): Promise<Brand> => {
    const response = await apiClient.get<Brand>(`/api/v1/brands/name/${encodeURIComponent(brandName)}`);
    return response.data;
  },

  // Get top brands by mention count
  getTopBrands: async (limit: number = 10, skip: number = 0): Promise<PaginatedResponse<Brand>> => {
    const response = await apiClient.get<PaginatedResponse<Brand>>(`/api/v1/public/brands/top?limit=${limit}&skip=${skip}`);
    return response.data;
  },

  // Get feeds linked to a brand (Brand 360)
  getBrandFeeds: async (brandId: string, autoGeneratedOnly: boolean = false): Promise<Feed[]> => {
    const response = await apiClient.get<Feed[]>(
      `/api/v1/brands/${brandId}/feeds?auto_generated_only=${autoGeneratedOnly}`
    );
    return response.data;
  },

  // Regenerate feeds for a brand (Brand 360)
  regenerateBrandFeeds: async (brandId: string): Promise<Feed[]> => {
    const response = await apiClient.post<Feed[]>(`/api/v1/brands/${brandId}/regenerate-feeds`);
    return response.data;
  },
};
